<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class BackendAdminFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name_english'      => 'required|regex:/^[a-zA-Z0-9\s]+$/',
            'name_bangla'       => 'required|regex:/^[a-zA-Z0-9\s]+$/',
            'username'          => 'required|unique:admins|regex:/^[a-zA-Z0-9\s]+$/',
            'email'             => 'required|email|unique:admins',
            'phone'             => 'required|unique:admins|regex:/(01)[0-9]{9}/',
            'dob'               => 'required|date',
            'gender'            => 'required',
            'religion'          => 'required',
            'image'             => 'image',
        ];
    }

    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'name_english.required'     => 'Please provide your name in English',
            'name_bangla.required'      => 'Please provide your name in Bangla',
            'username.required'         => 'Please provide a user name',
            'username.unique'           => 'User name already exists. Please try a different one',
            'phone.required'            => 'Please provide phone number',
            'gender.required'           => 'Please select a gender',
            'religion.required'         => 'Please select a religion',
        ];
    }
}
