<?php

namespace App\Models\Backend\Quran;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class QuranChapter extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'arabic_name',
        'bangla_name',
        'english_name',
        'chapter_serial',
        'total_verse',
        'surah_origin',
        'slug',
        'status',
    ];

    protected $searchableFields = ['*'];

    protected $table = 'quran_chapters';

    protected static $chapter;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($quranChapter){
//            if (isset($quranChapter->quranVerses))
//            {
//                $quranChapter->quranVerses->each->delete();
//            }
        });
    }

    public static function updateData($request,$id){
        self::$chapter = QuranChapter::find($id);
        self::insertData($request, self::$chapter);

    }

    public static function saveData($request){
        self::$chapter = new QuranChapter();
        self::insertData($request, self::$chapter);
    }

    public static function insertData($request, $chapter=null){

        $chapter->arabic_name                 = $request->arabic_name;
        $chapter->bangla_name                 = $request->bangla_name;
        $chapter->english_name                = $request->english_name;
        $chapter->chapter_serial              = $request->chapter_serial;
        $chapter->total_verse                 = $request->total_verse;
        $chapter->surah_origin                = $request->surah_origin;
        $chapter->status                      = $request->status == 'on' ? 1 : 0;
        $chapter->slug                        = str_replace(' ', '-', $request->arabic_name);
        $chapter->save();
    }

//    public function quranVerses()
//    {
//        return $this->hasMany(QuranVerse::class);
//    }
//
//    public function quranTranslations()
//    {
//        return $this->hasMany(QuranTranslation::class);
//    }
}
